package RSA;

import java.math.BigInteger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Elitebook
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        cifrado_1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tamano = new javax.swing.JTextField();
        Numero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BCifrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Decifrado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cifrado = new javax.swing.JTextArea();

        cifrado_1.setColumns(20);
        cifrado_1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        cifrado_1.setRows(5);
        jScrollPane2.setViewportView(cifrado_1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("BIENVENIDO AL CIFRADO RSA");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("INTRODUZCA EL TAMAÑO DE LOS NUMEROS PRIMOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        Tamano.setBackground(new java.awt.Color(29, 26, 26));
        Tamano.setForeground(new java.awt.Color(255, 255, 255));
        Tamano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 0, 153)));
        Tamano.setCaretColor(new java.awt.Color(255, 255, 255));
        Tamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamanoActionPerformed(evt);
            }
        });
        getContentPane().add(Tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 110, 30));

        Numero.setBackground(new java.awt.Color(29, 26, 26));
        Numero.setForeground(new java.awt.Color(255, 255, 255));
        Numero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 0, 153)));
        Numero.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 110, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("INTRODUZCA EL NUMERO A CIFRAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 441, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        BCifrar.setBackground(new java.awt.Color(0, 153, 153));
        BCifrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BCifrar.setText("CIFRAR");
        BCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCifrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("CIFRADO");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("DECIFRADO");

        Decifrado.setBackground(new java.awt.Color(29, 26, 26));
        Decifrado.setForeground(new java.awt.Color(255, 255, 255));
        Decifrado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 0, 153)));
        Decifrado.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        Cifrado.setBackground(new java.awt.Color(29, 26, 26));
        Cifrado.setColumns(20);
        Cifrado.setForeground(new java.awt.Color(255, 255, 255));
        Cifrado.setRows(5);
        Cifrado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 0, 153)));
        Cifrado.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(Cifrado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(218, 218, 218))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Decifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCifrar)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(BCifrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCifrarActionPerformed
        // TODO add your handling code here:
        String mensaje = Numero.getText();
        String tamanio = Tamano.getText();
        int num, lon_bits = 0;
        if(verificar(mensaje, tamanio)){
            num = Integer.parseInt(tamanio);
            
            switch(num){
                case 1:
                    lon_bits = 3;
                    break;
                case 2:
                    lon_bits = 7;
                    break;
                case 3:
                    lon_bits = 10;
                    break;
            }
            RSA Cifrar = new RSA(lon_bits);
            Cifrar.generarPrimos();
            Cifrar.generarClaves();
            BigInteger[] res_cifrar = Cifrar.cifrar(mensaje);
            String descifrado = Cifrar.descifrar(res_cifrar);
            Decifrado.setText(descifrado);
            String cifrado = "";
            for(int i = 0; i < res_cifrar.length; ++i){
                cifrado += res_cifrar[i];
                cifrado += "\n";
            }
            Cifrado.setText(cifrado);
        }
    }//GEN-LAST:event_BCifrarActionPerformed

    private void TamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamanoActionPerformed
    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    boolean verificar(String numero, String tamanio){
        String expresion_regular = "^[0-9]+$";
        if(tamanio.equals("") || numero.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor llene los campos");
        }
        if(!numero.matches(expresion_regular) || !numero.matches(expresion_regular)){
            JOptionPane.showMessageDialog(null, "Por favor ingresar solo numeros");
            return false;
        }
        int num = Integer.parseInt(tamanio);
        if(!(num >= 1 && num <= 3)){
           JOptionPane.showMessageDialog(null, "La longitud de los numeros primos debe de ser entre 1 y 3");
           return false;
        }
        
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCifrar;
    private javax.swing.JTextArea Cifrado;
    private javax.swing.JTextField Decifrado;
    private javax.swing.JTextField Numero;
    private javax.swing.JTextField Tamano;
    private javax.swing.JTextArea cifrado_1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
